### ISSUE TITLE
[1주차] Array & List & Time Complexity

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#1]
1주차 필수 문제
- [x] [최댓값](https://www.acmicpc.net/problem/2562)
- [x] [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
- [x] [요세푸스 문제](https://www.acmicpc.net/problem/1158)
- [x] [행운의 바퀴](https://www.acmicpc.net/problem/2840)
- [x] [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
- [x] [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)

1주차 선택 문제
- [x] [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by DoongPark** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [x]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [x]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [x]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [x]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [x]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by woogie01** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [x]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [x]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [x]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [x]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [x]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by kkh041124** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [ ]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [ ]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [ ]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [ ]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [ ]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by rhrudska987** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [x]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [x]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [x]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [x]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [x]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by youngjin0305** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [x]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [x]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [x]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [x]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [x]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [x]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by KimDa99** [comment]
> 1주차 필수 문제
> 
> * [x]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [x]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [x]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [ ]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [x]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [ ]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)

**Comment by kkh041124** [comment]
> 1주차 필수 문제
> 
> * [ ]  [최댓값](https://www.acmicpc.net/problem/2562)
> * [ ]  [2차원 배열의 합](https://www.acmicpc.net/problem/2167)
> * [ ]  [요세푸스 문제](https://www.acmicpc.net/problem/1158)
> * [ ]  [행운의 바퀴](https://www.acmicpc.net/problem/2840)
> * [ ]  [알고리즘 수업 - 알고리즘의 수행 시간 6](https://www.acmicpc.net/problem/24267)
> * [ ]  [알고리즘 수업 - 점근적 표기 1](https://www.acmicpc.net/problem/24313)
> 
> 1주차 선택 문제
> 
> * [ ]  [알고리즘 수업 - 점근적 표기 4](https://www.acmicpc.net/problem/24368)
