### ISSUE TITLE
[2주차] Stack & Queue

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#2]
2주차 필수 문제
- [x] [스택](https://www.acmicpc.net/problem/10828)
- [x] [스택 수열](https://www.acmicpc.net/problem/1874)
- [x] [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
- [x] [큐](https://www.acmicpc.net/problem/10845)
- [x] [카드2](https://www.acmicpc.net/problem/2164)
- [x] [좋은 친구](https://www.acmicpc.net/problem/3078)

2주차 선택 문제
- [x] [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by youngjin0305** [comment]
> 2주차 필수 문제
> 
> * [x]  [스택](https://www.acmicpc.net/problem/10828)
> * [x]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [x]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [x]  [큐](https://www.acmicpc.net/problem/10845)
> * [x]  [카드2](https://www.acmicpc.net/problem/2164)
> * [x]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by DoongPark** [comment]
> 2주차 필수 문제
> 
> * [x]  [스택](https://www.acmicpc.net/problem/10828)
> * [x]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [x]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [x]  [큐](https://www.acmicpc.net/problem/10845)
> * [x]  [카드2](https://www.acmicpc.net/problem/2164)
> * [x]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by 0HyerinPark** [comment]
> 2주차 필수 문제
> 
> * [x]  [스택](https://www.acmicpc.net/problem/10828)
> * [x]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [x]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [x]  [큐](https://www.acmicpc.net/problem/10845)
> * [x]  [카드2](https://www.acmicpc.net/problem/2164)
> * [x]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by rhrudska987** [comment]
> 2주차 필수 문제
> 
> * [x]  [스택](https://www.acmicpc.net/problem/10828)
> * [x]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [x]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [x]  [큐](https://www.acmicpc.net/problem/10845)
> * [x]  [카드2](https://www.acmicpc.net/problem/2164)
> * [x]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by woogie01** [comment]
> 2주차 필수 문제
> 
> * [x]  [스택](https://www.acmicpc.net/problem/10828)
> * [x]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [x]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [x]  [큐](https://www.acmicpc.net/problem/10845)
> * [x]  [카드2](https://www.acmicpc.net/problem/2164)
> * [ ]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)

**Comment by KimDa99** [comment]
> 2주차 필수 문제
> 
> * [ ]  [스택](https://www.acmicpc.net/problem/10828)
> * [ ]  [스택 수열](https://www.acmicpc.net/problem/1874)
> * [ ]  [외계인의 기타 연주](https://www.acmicpc.net/problem/2841)
> * [ ]  [큐](https://www.acmicpc.net/problem/10845)
> * [ ]  [카드2](https://www.acmicpc.net/problem/2164)
> * [ ]  [좋은 친구](https://www.acmicpc.net/problem/3078)
> 
> 2주차 선택 문제
> 
> * [ ]  [가운데를 말해요](https://www.acmicpc.net/problem/1655)
