### ISSUE TITLE
[3주차] 완전 탐색, 이분 탐색

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#3]
3주차 필수 문제
- [x] [영화감독 숌](https://www.acmicpc.net/problem/1436)
- [x] [마인크래프트](https://www.acmicpc.net/problem/18111)
- [x] [부분수열의 합](https://www.acmicpc.net/problem/14225)
- [x] [예산](https://www.acmicpc.net/problem/2512)
- [x] [나무 자르기](https://www.acmicpc.net/problem/2805)
- [x] [기타 레슨](https://www.acmicpc.net/problem/2343)

3주차 선택 문제
- [x] [공유기 설치](https://www.acmicpc.net/problem/2110)

**Comment by youngjin0305** [comment]
> 3주차 필수 문제
> 
> * [x]  [영화감독 숌](https://www.acmicpc.net/problem/1436)
> * [x]  [마인크래프트](https://www.acmicpc.net/problem/18111)
> * [ ]  [부분수열의 합](https://www.acmicpc.net/problem/14225)
> * [ ]  [예산](https://www.acmicpc.net/problem/2512)
> * [x]  [나무 자르기](https://www.acmicpc.net/problem/2805)
> * [x]  [기타 레슨](https://www.acmicpc.net/problem/2343)
> 
> 3주차 선택 문제
> 
> * [ ]  [공유기 설치](https://www.acmicpc.net/problem/2110)

**Comment by rhrudska987** [comment]
> 3주차 필수 문제
> 
> * [x]  [영화감독 숌](https://www.acmicpc.net/problem/1436)
> * [ ]  [마인크래프트](https://www.acmicpc.net/problem/18111)
> * [x]  [부분수열의 합](https://www.acmicpc.net/problem/14225)
> * [x]  [예산](https://www.acmicpc.net/problem/2512)
> * [x]  [나무 자르기](https://www.acmicpc.net/problem/2805)
> * [x]  [기타 레슨](https://www.acmicpc.net/problem/2343)
> 
> 3주차 선택 문제
> 
> * [ ]  [공유기 설치](https://www.acmicpc.net/problem/2110)

**Comment by woogie01** [comment]
> 3주차 필수 문제
> 
> * [ ]  [영화감독 숌](https://www.acmicpc.net/problem/1436)
> * [ ]  [마인크래프트](https://www.acmicpc.net/problem/18111)
> * [ ]  [부분수열의 합](https://www.acmicpc.net/problem/14225)
> * [ ]  [예산](https://www.acmicpc.net/problem/2512)
> * [ ]  [나무 자르기](https://www.acmicpc.net/problem/2805)
> * [ ]  [기타 레슨](https://www.acmicpc.net/problem/2343)
> 
> 3주차 선택 문제
> 
> * [ ]  [공유기 설치](https://www.acmicpc.net/problem/2110)

**Comment by 0HyerinPark** [comment]
> 3주차 필수 문제
> 
> * [x]  [영화감독 숌](https://www.acmicpc.net/problem/1436)
> * [ ]  [마인크래프트](https://www.acmicpc.net/problem/18111)
> * [x]  [부분수열의 합](https://www.acmicpc.net/problem/14225)
> * [ ]  [예산](https://www.acmicpc.net/problem/2512)
> * [ ]  [나무 자르기](https://www.acmicpc.net/problem/2805)
> * [ ]  [기타 레슨](https://www.acmicpc.net/problem/2343)
> 
> 3주차 선택 문제
> 
> * [ ]  [공유기 설치](https://www.acmicpc.net/problem/2110)

**Comment by DoongPark** [comment]
> 3주차 필수 문제
> 
> * [x]  [영화감독 숌](https://www.acmicpc.net/problem/1436)
> * [x]  [마인크래프트](https://www.acmicpc.net/problem/18111)
> * [x]  [부분수열의 합](https://www.acmicpc.net/problem/14225)
> * [x]  [예산](https://www.acmicpc.net/problem/2512)
> * [x]  [나무 자르기](https://www.acmicpc.net/problem/2805)
> * [ ]  [기타 레슨](https://www.acmicpc.net/problem/2343)
> 
> 3주차 선택 문제
> 
> * [ ]  [공유기 설치](https://www.acmicpc.net/problem/2110)
