### ISSUE TITLE
[4주차] 분할 정복

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#4]
4주차 필수 문제
- [x] [수 찾기](https://www.acmicpc.net/problem/1920)
- [x] [색종이 만들기](https://www.acmicpc.net/problem/2630)
- [x] [곱셈](https://www.acmicpc.net/problem/1629)
- [x] [행렬 제곱](https://www.acmicpc.net/problem/10830)
- [x] [Z](https://www.acmicpc.net/problem/1074)
- [x] [하노이 탑](https://www.acmicpc.net/problem/1914)
 
이번 주는 선택 문제가 없습니다. 😢 😢

**Comment by youngjin0305** [comment]
> 4주차 필수 문제
> 
> * [x]  [수 찾기](https://www.acmicpc.net/problem/1920)
> * [x]  [색종이 만들기](https://www.acmicpc.net/problem/2630)
> * [x]  [곱셈](https://www.acmicpc.net/problem/1629)
> * [ ]  [행렬 제곱](https://www.acmicpc.net/problem/10830)
> * [x]  [Z](https://www.acmicpc.net/problem/1074)
> * [ ]  [하노이 탑](https://www.acmicpc.net/problem/1914)
> 
> 이번 주는 선택 문제가 없습니다. 😢 😢

**Comment by DoongPark** [comment]
> 4주차 필수 문제
> 
> * [x]  [수 찾기](https://www.acmicpc.net/problem/1920)
> * [x]  [색종이 만들기](https://www.acmicpc.net/problem/2630)
> * [x]  [곱셈](https://www.acmicpc.net/problem/1629)
> * [ ]  [행렬 제곱](https://www.acmicpc.net/problem/10830)
> * [ ]  [Z](https://www.acmicpc.net/problem/1074)
> * [ ]  [하노이 탑](https://www.acmicpc.net/problem/1914)
> 
> 이번 주는 선택 문제가 없습니다. 😢 😢

**Comment by woogie01** [comment]
> 4주차 필수 문제
> 
> * [x]  [수 찾기](https://www.acmicpc.net/problem/1920)
> * [x]  [색종이 만들기](https://www.acmicpc.net/problem/2630)
> * [ ]  [곱셈](https://www.acmicpc.net/problem/1629)
> * [ ]  [행렬 제곱](https://www.acmicpc.net/problem/10830)
> * [ ]  [Z](https://www.acmicpc.net/problem/1074)
> * [ ]  [하노이 탑](https://www.acmicpc.net/problem/1914)
> 
> 이번 주는 선택 문제가 없습니다. 😢 😢

**Comment by rhrudska987** [comment]
> 4주차 필수 문제
> 
> * [x]  [수 찾기](https://www.acmicpc.net/problem/1920)
> * [x]  [색종이 만들기](https://www.acmicpc.net/problem/2630)
> * [ ]  [곱셈](https://www.acmicpc.net/problem/1629)
> * [ ]  [행렬 제곱](https://www.acmicpc.net/problem/10830)
> * [x]  [Z](https://www.acmicpc.net/problem/1074)
> * [ ]  [하노이 탑](https://www.acmicpc.net/problem/1914)
> 
> 이번 주는 선택 문제가 없습니다. 😢 😢
