### ISSUE TITLE
[5주차] Greedy

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#5]
5주차 필수 문제
- [x]  [동전 0](https://www.acmicpc.net/problem/11047)
- [x] [주유소](https://www.acmicpc.net/problem/13305)
- [x] [A → B](https://www.acmicpc.net/problem/16953)
- [x] [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
- [x] [회의실 배정](https://www.acmicpc.net/problem/1931)
- [x] [행렬](https://www.acmicpc.net/problem/1080)

5주차 선택 문제
- [ ] [공항](https://www.acmicpc.net/problem/10775)

**Comment by youngjin0305** [comment]
> 5주차 필수 문제
> 
> * [x]   [동전 0](https://www.acmicpc.net/problem/11047)
> * [x]  [주유소](https://www.acmicpc.net/problem/13305)
> * [x]  [A → B](https://www.acmicpc.net/problem/16953)
> * [x]  [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
> * [x]  [회의실 배정](https://www.acmicpc.net/problem/1931)
> * [x]  [행렬](https://www.acmicpc.net/problem/1080)
> 
> 5주차 선택 문제
> 
> * [ ]  [공항](https://www.acmicpc.net/problem/10775)

**Comment by rhrudska987** [comment]
> 5주차 필수 문제
> 
> * [x]   [동전 0](https://www.acmicpc.net/problem/11047)
> * [x]  [주유소](https://www.acmicpc.net/problem/13305)
> * [x]  [A → B](https://www.acmicpc.net/problem/16953)
> * [x]  [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
> * [x]  [회의실 배정](https://www.acmicpc.net/problem/1931)
> * [x]  [행렬](https://www.acmicpc.net/problem/1080)
> 
> 5주차 선택 문제
> 
> * [x]  [공항](https://www.acmicpc.net/problem/10775)

**Comment by DoongPark** [comment]
> 5주차 필수 문제
> 
> * [x]   [동전 0](https://www.acmicpc.net/problem/11047)
> * [x]  [주유소](https://www.acmicpc.net/problem/13305)
> * [x]  [A → B](https://www.acmicpc.net/problem/16953)
> * [x]  [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
> * [x]  [회의실 배정](https://www.acmicpc.net/problem/1931)
> * [x]  [행렬](https://www.acmicpc.net/problem/1080)
> 
> 5주차 선택 문제
> 
> * [ ]  [공항](https://www.acmicpc.net/problem/10775)

**Comment by 0HyerinPark** [comment]
> 5주차 필수 문제
> 
> * [x]   [동전 0](https://www.acmicpc.net/problem/11047)
> * [x]  [주유소](https://www.acmicpc.net/problem/13305)
> * [x]  [A → B](https://www.acmicpc.net/problem/16953)
> * [x]  [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
> * [ ]  [회의실 배정](https://www.acmicpc.net/problem/1931)
> * [ ]  [행렬](https://www.acmicpc.net/problem/1080)
> 
> 5주차 선택 문제
> 
> * [ ]  [공항](https://www.acmicpc.net/problem/10775)

**Comment by woogie01** [comment]
> 5주차 필수 문제
> 
> * [x]   [동전 0](https://www.acmicpc.net/problem/11047)
> * [x]  [주유소](https://www.acmicpc.net/problem/13305)
> * [x]  [A → B](https://www.acmicpc.net/problem/16953)
> * [x]  [잃어버린 괄호](https://www.acmicpc.net/problem/1541)
> * [x]  [회의실 배정](https://www.acmicpc.net/problem/1931)
> * [ ]  [행렬](https://www.acmicpc.net/problem/1080)
> 
> 5주차 선택 문제
> 
> * [ ]  [공항](https://www.acmicpc.net/problem/10775)
