### ISSUE TITLE
[6주차] DP

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#6]
6주차 필수 문제
- [x] [파도반 수열](https://www.acmicpc.net/problem/9461)
- [x] [1로 만들기](https://www.acmicpc.net/problem/1463)
- [x] [제곱수의 합](https://www.acmicpc.net/problem/1699)
- [x] [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
- [x] [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
- [x] [동전 2](https://www.acmicpc.net/problem/2294)

6주차 선택 문제(우리 학교 2022년 2학기 알고리즘 대회에서 나왔던 문제입니다.)
- [ ] [들판 건너가기](https://www.acmicpc.net/problem/25759)

**Comment by DoongPark** [comment]
> 6주차 필수 문제
> 
> * [x]  [파도반 수열](https://www.acmicpc.net/problem/9461)
> * [x]  [1로 만들기](https://www.acmicpc.net/problem/1463)
> * [x]  [제곱수의 합](https://www.acmicpc.net/problem/1699)
> * [x]  [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
> * [x]  [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
> * [ ]  [동전 2](https://www.acmicpc.net/problem/2294)
> 
> 6주차 선택 문제(우리 학교 2022년 2학기 알고리즘 대회에서 나왔던 문제입니다.)
> 
> * [ ]  [들판 건너가기](https://www.acmicpc.net/problem/25759)

**Comment by youngjin0305** [comment]
> 6주차 필수 문제
> 
> * [x]  [파도반 수열](https://www.acmicpc.net/problem/9461)
> * [x]  [1로 만들기](https://www.acmicpc.net/problem/1463)
> * [x]  [제곱수의 합](https://www.acmicpc.net/problem/1699)
> * [x]  [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
> * [x]  [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
> * [x]  [동전 2](https://www.acmicpc.net/problem/2294)
> 
> 6주차 선택 문제(우리 학교 2022년 2학기 알고리즘 대회에서 나왔던 문제입니다.)
> 
> * [ ]  [들판 건너가기](https://www.acmicpc.net/problem/25759)

**Comment by rhrudska987** [comment]
> 6주차 필수 문제
> 
> * [x]  [파도반 수열](https://www.acmicpc.net/problem/9461)
> * [x]  [1로 만들기](https://www.acmicpc.net/problem/1463)
> * [x]  [제곱수의 합](https://www.acmicpc.net/problem/1699)
> * [ ]  [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
> * [ ]  [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
> * [ ]  [동전 2](https://www.acmicpc.net/problem/2294)
> 
> 6주차 선택 문제(우리 학교 2022년 2학기 알고리즘 대회에서 나왔던 문제입니다.)
> 
> * [ ]  [들판 건너가기](https://www.acmicpc.net/problem/25759)

**Comment by 0HyerinPark** [comment]
> 6주차 필수 문제
> 
> * [x]  [파도반 수열](https://www.acmicpc.net/problem/9461)
> * [ ]  [1로 만들기](https://www.acmicpc.net/problem/1463)
> * [ ]  [제곱수의 합](https://www.acmicpc.net/problem/1699)
> * [ ]  [쉬운 계단 수](https://www.acmicpc.net/problem/10844)
> * [ ]  [구간 합 구하기 5](https://www.acmicpc.net/problem/11660)
> * [ ]  [동전 2](https://www.acmicpc.net/problem/2294)
> 
> 6주차 선택 문제(우리 학교 2022년 2학기 알고리즘 대회에서 나왔던 문제입니다.)
> 
> * [ ]  [들판 건너가기](https://www.acmicpc.net/problem/25759)
