### ISSUE TITLE
[7주차] BackTracking & DFS

### ISSUE THREAD

**Issue by shchooii** [TeamCrazyPerformance/Algorithm_Basic#7]
7주차 필수 문제
- [x] [N과 M (1)](https://www.acmicpc.net/problem/15649)
- [x] [N-Queen](https://www.acmicpc.net/problem/9663)
- [x] [알고리즘 수업 - 깊이 우선 탐색 1](https://www.acmicpc.net/problem/24479)
- [x] [알고리즘 수업 - 깊이 우선 탐색 2](https://www.acmicpc.net/problem/24480)
- [x] [유기농 배추](https://www.acmicpc.net/problem/1012)
- [x] [경로 찾기](https://www.acmicpc.net/problem/11403)

이번주는 선택 문제가 없습니다. 😢 😢

**Comment by rhrudska987** [comment]
> 7주차 필수 문제
> 
> * [x]  [N과 M (1)](https://www.acmicpc.net/problem/15649)
> * [x]  [N-Queen](https://www.acmicpc.net/problem/9663)
> * [x]  [알고리즘 수업 - 깊이 우선 탐색 1](https://www.acmicpc.net/problem/24479)
> * [x]  [알고리즘 수업 - 깊이 우선 탐색 2](https://www.acmicpc.net/problem/24480)
> * [x]  [유기농 배추](https://www.acmicpc.net/problem/1012)
> * [x]  [경로 찾기](https://www.acmicpc.net/problem/11403)
> 
> 이번주는 선택 문제가 없습니다. 😢 😢

**Comment by youngjin0305** [comment]
> 7주차 필수 문제
> 
> * [x]  [N과 M (1)](https://www.acmicpc.net/problem/15649)
> * [x]  [N-Queen](https://www.acmicpc.net/problem/9663)
> * [x]  [알고리즘 수업 - 깊이 우선 탐색 1](https://www.acmicpc.net/problem/24479)
> * [x]  [알고리즘 수업 - 깊이 우선 탐색 2](https://www.acmicpc.net/problem/24480)
> * [x]  [유기농 배추](https://www.acmicpc.net/problem/1012)
> * [x]  [경로 찾기](https://www.acmicpc.net/problem/11403)
> 
> 이번주는 선택 문제가 없습니다. 😢 😢
